#!/usr/bin/env python3
"""
Untested CMake to Redwood BUILD.datalog Generator

Converts CMake's compile_commands.json to BUILD.datalog format.
Usage:
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /path/to/source
    python3 cmake_to_redwood.py build/compile_commands.json > BUILD.datalog
"""

import json
import os
import sys
import hashlib
from pathlib import Path
from typing import Dict, List, Set, Tuple


def escape_datalog_string(s: str) -> str:
    """Escape a string for Datalog syntax."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def normalize_path(path: str, build_dir: str) -> str:
    """Normalize path relative to build directory."""
    path = os.path.abspath(path)
    build_dir = os.path.abspath(build_dir)
    try:
        return os.path.relpath(path, build_dir)
    except ValueError:
        return path


def parse_compile_command(cmd: Dict) -> Tuple[str, str, List[str], str, str]:
    """
    Parse a compile command entry.
    Returns: (compiler, source_file, flags, output_file, directory)
    """
    source = cmd.get('file', '')
    directory = cmd.get('directory', '.')
    command = cmd.get('command', '')
    output = cmd.get('output', '')

    import shlex
    parts = shlex.split(command)

    compiler_path = parts[0] if parts else 'gcc'
    compiler = os.path.basename(compiler_path)

    if compiler in ['clang++', 'c++']:
        compiler = 'g++'
    elif compiler in ['clang', 'cc']:
        compiler = 'gcc'

    flags = []

    i = 1
    while i < len(parts):
        part = parts[i]

        if part == source or part.endswith(source):
            i += 1
            continue

        if part == '-o' and i + 1 < len(parts):
            output = parts[i + 1]
            i += 2
            continue

        if part.startswith('-'):
            if part == '-c':
                i += 1
                continue

            if part in ['-I', '-D', '-isystem', '-include', '-std', '-march', '-mtune'] and i + 1 < len(parts):
                next_part = parts[i + 1]
                if not next_part.startswith('-'):
                    flags.append(f"{part} {next_part}")
                    i += 2
                    continue

            flags.append(part)

        i += 1

    return compiler, source, flags, output, directory


def generate_target_label(output_file: str, build_dir: str) -> str:
    """Generate a Redwood target label for an output file."""
    # Normalize path
    rel_path = normalize_path(output_file, build_dir)

    # Create target label: //dir/subdir:filename
    path_parts = Path(rel_path).parts
    if len(path_parts) > 1:
        directory = '/'.join(path_parts[:-1])
        filename = path_parts[-1]
        return f"//{directory}:{filename}"
    else:
        return f"//:{rel_path}"


def infer_dependencies(source: str, build_dir: str, all_outputs: Set[str]) -> List[str]:
    return []


def generate_datalog(compile_commands: List[Dict], build_dir: str) -> str:
    """Generate BUILD.datalog from compile_commands.json"""

    lines = [
        "# Generated by cmake_to_redwood.py",
        "# Source: compile_commands.json",
        "",
    ]

    all_outputs = set()
    commands_by_output = {}

    for cmd in compile_commands:
        compiler, source, flags, output, directory = parse_compile_command(cmd)
        if output:
            all_outputs.add(output)
            commands_by_output[output] = (source, flags, directory, cmd)

    for output, (source, flags, directory, cmd) in commands_by_output.items():
        compiler, source, flags, output, directory = parse_compile_command(cmd)
        target_label = generate_target_label(output, build_dir)

        source_abs = os.path.abspath(os.path.join(directory, source))
        source_rel = source_abs

        output_rel = normalize_path(output, build_dir)

        lines.append(f'# Target: {target_label}')
        lines.append(f'target("{escape_datalog_string(target_label)}").')
        lines.append(f'kind("{escape_datalog_string(target_label)}", system_tool).')
        lines.append(f'attr("{escape_datalog_string(target_label)}", "tool", "{escape_datalog_string(compiler)}").')
        lines.append(f'attr("{escape_datalog_string(target_label)}", "-o", "{{output}}").')
        lines.append(f'attr("{escape_datalog_string(target_label)}", "-c", "{{sources}}").')

        for flag in flags:
            lines.append(f'attr("{escape_datalog_string(target_label)}", "{escape_datalog_string(flag)}", "").')

        lines.append(f'sources("{escape_datalog_string(target_label)}", "{escape_datalog_string(source_rel)}").')
        lines.append(f'outputs("{escape_datalog_string(target_label)}", "{escape_datalog_string(output_rel)}").')

        # Infer dependencies (simplified - real implementation needs more work)
        deps = infer_dependencies(source, build_dir, all_outputs)
        for dep in deps:
            dep_label = generate_target_label(dep, build_dir)
            lines.append(f'deps("{escape_datalog_string(target_label)}", "{escape_datalog_string(dep_label)}").')

        lines.append('')

    return '\n'.join(lines)


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <compile_commands.json>", file=sys.stderr)
        print("", file=sys.stderr)
        print("Example:", file=sys.stderr)
        print("  cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..", file=sys.stderr)
        print(f"  python3 {sys.argv[0]} compile_commands.json > BUILD.datalog", file=sys.stderr)
        sys.exit(1)

    compile_commands_path = sys.argv[1]
    build_dir = os.path.dirname(os.path.abspath(compile_commands_path))

    if not os.path.exists(compile_commands_path):
        print(f"Error: {compile_commands_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(compile_commands_path, 'r') as f:
        compile_commands = json.load(f)

    datalog = generate_datalog(compile_commands, build_dir)
    print(datalog)


if __name__ == '__main__':
    main()
